### ISSUE TITLE
`run()` method should not be returning Promise

### ISSUE THREAD

**Issue by john5f35** [hbenl/vscode-test-adapter-api#2]
Hi,
It seems to me that `run(tests: string[]): Promise<void>` method should not be returning a `Promise`. In the [TestExplorer implementation](https://github.com/hbenl/vscode-test-explorer/blob/master/src/testExplorer.ts#L109), `run()` is called as a synchronous function. I can't properly return an error if running the test has somehow failed unexpectedly (not the test result as failed, but failed to *run* the test).

It's either the implementation should be modified to return the promise from test adapter, or it should just be a synchronous function.

Please fix.

**Comment by matepek** [comment]
I would like to add a comment to this.

Personally it is not necessary for my extension right now, but if there will be any solution, a general one maybe better. 

Example num1: `TestSuiteEvent` having an `errored` state and `errorMessage` property.
I think the adapter should handle all the errors (so Promise<void> is fine), because the Explorer cannot.

What do you think @john5f35 ? Would that example solve your problem?

Also, there is a situation when I load the tests, but a suit contains some error (for example duplicated test names). In this case now I'm adding a [dummy](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/src/Catch2TestSuiteInfo.ts#L55) test to the suite, to enlighten the user about the problem. I could imagine a better way to to this. In case of *Example num1* i could send a `TestSuiteEvent` with the error message and yellow exclamation mark could mark the wrong suite.

**Comment by hbenl** [comment]
The `Promise` that the `run(...)` method returns is purely for convenience, it's not currently being used by the Test Explorer, but could be used by it or other Test Controllers in the future. In any case, I don't see any harm in returning it, even if it's currently unused.
The real "source of truth" are the `testStates` events, so the error reporting should be added there. I agree with the proposal by @matepek and will implement it (unless you see any problems or have a better idea).

**Comment by john5f35** [comment]
@matepek, @hbenl, I guess the suggestion would work for my case. I'm still working my way through writing a test adapter, and I haven't quite touched on `TestSuiteEvent` and the intended error handling way yet. I'm looking forward to the implementation of the above suggestion.

**Comment by hbenl** [comment]
FYI: In version 1.2.0 of the TestAdapter API I have added the `errored` state to the `TestEvent`. I have decided against adding it to the `TestSuiteEvent` because the Test Explorer currently doesn't attach a state to the suites (the state displayed for a test suite is always computed from the states of the tests it contains, and nothing else). So, if you want to tell the Test Explorer that a test suite failed to run, you need to send `errored` events for all the tests in that suite.

**Comment by matepek** [comment]
The only thing is that I still need a dummy test. But I'm fine with it.
