### ISSUE TITLE
Traverse up test node hierarchy

### ISSUE THREAD

**Issue by KamasamaK** [hbenl/vscode-test-adapter-api#3]
I find myself sometimes wanting to traverse up the hierarchy of `TestSuiteInfo` and `TestInfo` nodes. I could make subinterfaces with a new `parentId` property, but before doing so I was curious if you think it would be generally useful to accommodate this however you see best.

**Comment by matepek** [comment]
Hello, 
I was doing the same. Actually I was storing the parent itself as a reference.
It worked well.

**Comment by hbenl** [comment]
If I needed this in my adapter, I would also save a reference to the parent in the child. But if you do this, the test tree can't be serialized with `JSON.stringify()` anymore (due to circular references parent -> child -> parent), so you need to do this in a copy of the test tree. That's why I don't add this to the API, the test tree sent to the Test Explorer cannot contain those parent references.
